# Generated by Django 6.0.3 on 2026-04-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="issue_images/"),
        ),
        migrations.AddField(
            model_name="issue",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("water", "Water"),
                    ("electricity", "Electricity"),
                    ("road", "Road"),
                    ("waste", "Waste"),
                ],
                default="water",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
